services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:7.2
    ports:
      - "6379:6379" 

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - app
      - redis


  # flower:
  #  container_name: flower
  #  build: .
  #  command: celery -A celery_worker.celery flower --port=5555
  #  ports:
  #    - 5556:5555
  #  environment:
  #    - CELERY_BROKER_URL=${CELERY_BROKER_URL}
  #    - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
  #  depends_on:
  #    - app
  #    - redis
  #    - celery_worker
