services:

  app:
    container_name: app
    build: 
      context: . 
      dockerfile: Dockerfile.app
      target: development
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env

  celery_worker:
    container_name: celery_worker
    build: 
      context: .
      dockerfile: Dockerfile.worker
      target: development
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - app
      - redis

  redis:
    container_name: redis
    image: redis:7.2
    ports:
      - 6379:6379 
  
  db:
    image: postgres:16
    container_name: whatsboost-db
    restart: always
    ports:
      - 5433:5432
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data 
      
  adminer:
    image: adminer
    container_name: whatsboost-db-adminer
    restart: always
    ports:
      - 8080:8080
      
volumes:
  pgdata: 

  # flower:
  #  container_name: flower
  #  build: .
  #  command: celery -A celery_worker.celery flower --port=5555
  #  ports:
  #    - 5556:5555
  #  environment:
  #    - CELERY_BROKER_URL=${CELERY_BROKER_URL}
  #    - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
  #  depends_on:
  #    - app
  #    - redis
  #    - celery_worker