"""add new user columns

Revision ID: b4cde7f043f1
Revises: fdd6b2872955
Create Date: 2025-06-06 16:44:20.133779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4cde7f043f1'
down_revision: Union[str, None] = 'fdd6b2872955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('evo_instance_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('evo_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cloudinary_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cloudinary_secret_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('logo_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'logo_public_id')
    op.drop_column('users', 'cloudinary_secret_key')
    op.drop_column('users', 'cloudinary_api_key')
    op.drop_column('users', 'evo_api_key')
    op.drop_column('users', 'evo_instance_id')
    # ### end Alembic commands ###
